name: deprecate

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deprecate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # extract `engines.node` from package.json and save it to output
      - name: Get Node.JS version from package.json
        id: get-versions
        run: echo ::set-output name=node::$(jq -r .engines.node ./package.json)
      - name: Use Node.js ${{ steps.get-versions.outputs.node }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          # this line is required for the setup-node action to be able to run the npm publish below.
          registry-url: 'https://registry.npmjs.org'
          cache: yarn
      - run: npm deprecate @mux-elements/mux-player "This package has moved to the @mux/mux-player scope. See https://www.mux.com/blog/mux-elements-are-getting-a-new-old-home-on-npm-mux for more information."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm deprecate @mux-elements/mux-player-react "This package has moved to the @mux/mux-player-react scope. See https://www.mux.com/blog/mux-elements-are-getting-a-new-old-home-on-npm-mux for more information."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm deprecate @mux-elements/mux-uploader "This package has moved to the @mux/mux-uploader scope. See https://www.mux.com/blog/mux-elements-are-getting-a-new-old-home-on-npm-mux for more information."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
